//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OrchidHome0804.rc
//
#define IDS_GAN01                       101
#define IDS_GAN02                       102
#define IDS_GAN03                       103
#define IDS_GAN04                       104
#define IDS_GAN05                       105
#define IDS_GAN06                       106
#define IDS_GAN07                       107
#define IDS_GAN08                       108
#define IDS_GAN09                       109
#define IDS_GAN10                       110
#define IDS_ZHI01                       121
#define IDS_ZHI02                       122
#define IDS_ZHI03                       123
#define IDS_ZHI04                       124
#define IDS_ZHI05                       125
#define IDS_ZHI06                       126
#define IDS_ZHI07                       127
#define IDS_ZHI08                       128
#define IDS_ZHI09                       129
#define IDS_ZHI10                       130
#define IDS_ZHI11                       131
#define IDS_ZHI12                       132
#define IDS_SHENGXIAO01                 141
#define IDS_SHENGXIAO02                 142
#define IDS_SHENGXIAO03                 143
#define IDS_SHENGXIAO04                 144
#define IDS_SHENGXIAO05                 145
#define IDS_SHENGXIAO06                 146
#define IDS_SHENGXIAO07                 147
#define IDS_SHENGXIAO08                 148
#define IDS_SHENGXIAO09                 149
#define IDS_SHENGXIAO10                 150
#define IDS_SHENGXIAO11                 151
#define IDS_SHENGXIAO12                 152
#define IDS_XINGZUO01                   161
#define IDS_XINGZUO02                   162
#define IDS_XINGZUO03                   163
#define IDS_XINGZUO04                   164
#define IDS_XINGZUO05                   165
#define IDS_XINGZUO06                   166
#define IDS_XINGZUO07                   167
#define IDS_XINGZUO08                   168
#define IDS_XINGZUO09                   169
#define IDS_XINGZUO10                   170
#define IDS_XINGZUO11                   171
#define IDS_XINGZUO12                   172
#define IDS_JIEQI01                     201
#define IDS_JIEQI02                     202
#define IDS_JIEQI03                     203
#define IDS_JIEQI04                     204
#define IDS_JIEQI05                     205
#define IDS_JIEQI06                     206
#define IDS_JIEQI07                     207
#define IDS_JIEQI08                     208
#define IDS_JIEQI09                     209
#define IDS_JIEQI10                     210
#define IDS_JIEQI11                     211
#define IDS_JIEQI12                     212
#define IDS_JIEQI13                     213
#define IDS_JIEQI14                     214
#define IDS_JIEQI15                     215
#define IDS_JIEQI16                     216
#define IDS_JIEQI17                     217
#define IDS_JIEQI18                     218
#define IDS_JIEQI19                     219
#define IDS_JIEQI20                     220
#define IDS_JIEQI21                     221
#define IDS_JIEQI22                     222
#define IDS_JIEQI23                     223
#define IDS_JIEQI24                     224
#define IDS_NUM00                       230
#define IDS_NUM01                       231
#define IDS_NUM02                       232
#define IDS_NUM03                       233
#define IDS_NUM04                       234
#define IDS_NUM05                       235
#define IDS_NUM06                       236
#define IDS_NUM07                       237
#define IDS_NUM08                       238
#define IDS_NUM09                       239
#define IDS_NUM10                       240
#define IDS_NUM11                       241
#define IDS_NUM12                       242
#define IDS_DAY0                        250
#define IDS_DAY1                        251
#define IDS_DAY2                        252
#define IDS_DAY3                        253
#define IDS_ZUO                         300
#define IDS_GUANGXU                     301
#define IDS_XUANTONG                    302
#define IDS_MINGUO                      303
#define IDS_GONGYUAN                    304
#define IDS_YUAN                        305
#define IDS_NIAN                        306
#define IDS_LEAPMONTH                   307
#define IDS_MONTH                       308
#define IDS_BIGMONTH                    309
#define IDS_LITTLEMONTH                 310
#define IDS_WEEK                        311
#define IDS_SUNALLWAYSUP                312
#define IDS_SUNALLWAYSDOWN              313
#define IDS_SUNERROR                    314
#define IDS_UNKNOWN                     315
#define IDS_HIGH                        320
#define IDS_LOW                         321
#define IDS_CRITICAL                    322
#define IDS_CHARGING                    323
#define IDS_NONE                        324
#define IDS_ALKALINE                    325
#define IDS_NICD                        326
#define IDS_NIMH                        327
#define IDS_LIION                       328
#define IDS_LIPB                        329
#define IDS_CALENDER_INFO               330
#define IDS_SUN_INFO                    331
#define IDS_POWER_INFO                  332
#define IDS_POWER_INFO_BK               333
#define IDS_MEM_INFO                    334
#define IDS_STORAGE_INFO                335
#define IDS_HOLIDAY_INFO                336
#define IDS_ABOUT_INFO                  337
#define IDS_FORMAT_TIME                 340
#define IDS_CAP_ABOUT                   341
#define IDS_CAP_CALENDER                342
#define IDS_CAP_HOLIDAY                 343
#define IDS_CAP_POWER                   344
#define IDS_CAP_MEM                     345
#define IDS_CAP_OPTION                  347
#define IDS_CAP_ALARMS                  348
#define IDS_CAP_MONTHHOLIDAY            349
#define IDS_CAP_RESTART                 350
#define IDS_CAP_SHUTDOWN                351
#define IDS_TI_CALENDER                 355
#define IDS_TI_ALARM                    356
#define IDS_TI_USERDAY                  357
#define IDS_TI_TOOLS                    358
#define IDS_FMTHOLI_DATE                360
#define IDS_FMTHOLI_BIRTH               361
#define IDS_FMTHOLI_BIRTHL              362
#define IDS_FMTHOLI_LBIRTH              363
#define IDS_FMTHOLI_DAY                 364
#define IDS_FMTHOLI_DAYL                365
#define IDS_FMTHOLI_LDATE               366
#define IDS_FMTCAL_TODAY                367
#define IDS_FMTCAL_INFO                 368
#define IDS_FMTCAL_DAYCOUNT             369
#define IDS_FMTCAL_MONTHHOLIDAY         370
#define IDS_LD_SOLAR                    400
#define IDS_LD_LUNAR                    401
#define IDS_LD_WEEK                     402
#define IDS_LD_SOLARBIRTH               403
#define IDS_LD_LUNARBIRTH               404
#define IDS_LD_SOLARDAY                 405
#define IDS_LD_LUNARDAY                 406
#define IDS_LT_HOLIDAY                  410
#define IDS_LT_BIRTHDAY                 411
#define IDS_LT_REMDAY                   412
#define IDS_LF_SOLARDATE                413
#define IDS_LF_SOLARSHORT               414
#define IDS_LF_LUNARDATE                415
#define IDS_LF_LUNARSHORT               416
#define IDS_LF_WEEKDATE                 417
#define IDS_MSG_CLEAR                   420
#define IDS_MSG_INVALIDDATE             421
#define IDS_MSG_NAMEISEMPTY             422
#define IDS_MSG_INVALIDINT              423
#define IDS_MSG_EXECCONFIRM             424
#define IDS_LT_ALARM                    450
#define IDS_LT_EXECUTE                  451
#define IDS_LT_FLIGHTMODE               452
#define IDS_LT_SILENTMODE               453
#define IDS_LT_RESTART                  454
#define IDS_LT_POWEROFF                 455
#define IDS_LT_CHIME                    456
#define IDS_LT_ONCE                     460
#define IDS_LT_DAILY                    461
#define IDS_LT_WEEKDAYS                 462
#define IDS_LT_WEEKENDS                 463
#define IDS_LT_WEEKLY                   464
#define IDS_LT_MONTHLY                  465
#define IDS_LT_ANNUALLY                 466
#define IDS_LT_INTERVAL                 467
#define IDS_LT_RING                     470
#define IDS_LT_VIBRATE                  471
#define IDS_LT_BOTH                     472
#define IDS_LT_VIBRATEFIRST             473
#define IDS_LT_SNDFILEDEF               480
#define IDS_LT_VOLUMEDEF                481
#define IDS_LT_VOLUME0                  482
#define IDS_LT_VOLUME1                  483
#define IDS_LT_VOLUME2                  484
#define IDS_LT_VOLUME3                  485
#define IDS_LT_VOLUME4                  486
#define IDS_LT_VOLUME5                  487
#define IDS_LT_HOLIDAYLEVEL0            490
#define IDS_LT_HOLIDAYLEVEL1            491
#define IDS_LT_HOLIDAYLEVEL2            492
#define IDS_LT_HOLIDAYLEVEL3            493
#define IDC_LISTMAINALARM               1001
#define IDC_LISTMAINUSERDAY             1002
#define IDC_LISTMAINTOOLS               1003
#define IDC_LISTHOLITYPE                1005
#define IDC_EDITHOLINAME                1006
#define IDC_EDITHOLISHORT               1007
#define IDC_EDITYEAR                    1008
#define IDC_EDITWEEKMONTH               1009
#define IDC_EDITMONTH                   1010
#define IDC_EDITDAY                     1011
#define IDC_EDITWEEK                    1012
#define IDC_EDITWEEKDAY                 1013
#define IDC_TEXTYEAR                    1014
#define IDC_TEXTMONTH                   1015
#define IDC_TEXTDAY                     1016
#define IDC_TEXTWEEKMONTH               1017
#define IDC_TEXTWEEK                    1018
#define IDC_CHECKADDDAY                 1019
#define IDC_EDITLONGITUDE               1020
#define IDC_EDITLONGITUDE1              1021
#define IDC_EDITLATITUDE                1022
#define IDC_EDITLATITUDE1               1023
#define IDC_EDITZONETIME                1024
#define IDC_EDITTEMPERATURE             1025
#define IDC_CHECKTEMPERATURE            1026
#define IDC_LISTALARMTYPE               1027
#define IDC_EDITINFOINTERVAL            1028
#define IDC_LISTRECURTYPE               1029
#define IDC_CHECKCOUNTER                1030
#define IDC_ALARMDATE                   1031
#define IDC_LISTHOLIDAYLEVEL            1032
#define IDC_ALARMTIME                   1033
#define IDC_EDITCOUNTER                 1034
#define IDC_ALARMTIME2                  1035
#define IDC_EDITALARMTEXT               1036
#define IDC_EDITALARMTARGET             1037
#define IDC_LISTSNDFILE                 1038
#define IDC_LISTVOLUME                  1039
#define IDC_CHECKWEEK1                  1040
#define IDC_CHECKWEEK2                  1041
#define IDC_CHECKWEEK3                  1042
#define IDC_CHECKWEEK4                  1043
#define IDC_CHECKWEEK5                  1044
#define IDC_CHECKWEEK6                  1045
#define IDC_CHECKWEEK7                  1046
#define IDC_LBLENDTIME                  1047
#define IDC_LBLALARMWEEK                1048
#define IDC_LBLALARMMONTH               1049
#define IDC_EDITALARMMONTH              1050
#define IDC_CHECKALARMENABLED           1051
#define IDC_LISTALARMMODE               1052
#define IDC_DTPCOUNTER                  1053
#define IDC_LISTRINGCOUNT               1054
#define IDC_LBLALARMINTERVAL            1055
#define IDC_EDITALARMINTERVAL           1056
#define IDC_LBLALARMANNUALLY            1057
#define IDC_EDITALARMDAY                1058
#define IDC_LBLALARMMONTH1              1059
#define IDC_LBLALARMMONTH2              1060
#define IDC_LBLALARMINTERVAL1           1061
#define IDR_MENU_OKCANCEL               2001
#define IDR_MENU_MAIN                   2002
#define IDD_MAINDLG                     3001
#define IDD_EDITALARMDLG                3002
#define IDD_EDITDAYDLG                  3003
#define IDD_OPTIONDLG                   3004
#define IDS_OK                          40001
#define IDS_CLOSE                       40002
#define IDS_DISPLAY                     40003
#define IDS_EDIT                        40004
#define IDS_MENU                        40005
#define IDS_CANCEL                      40006
#define IDS_ACTION                      40007
#define IDM_OPTION                      40030
#define IDM_MAILTO                      40031
#define IDM_WEBSITE                     40032
#define IDM_ABOUT                       40033
#define IDM_LASTDAY                     40034
#define IDM_NEXTDAY                     40035
#define IDM_LASTWEEK                    40036
#define IDM_NEXTWEEK                    40037
#define IDM_LASTMONTH                   40038
#define IDM_NEXTMONTH                   40039
#define IDM_LASTYEAR                    40040
#define IDM_NEXTYEAR                    40041
#define IDM_GOTOTODAY                   40042
#define IDM_DAYDETAIL                   40043
#define IDM_MONTHHOLIDAY                40044
#define IDM_PAGECALENDAR                40050
#define IDM_PAGEALARM                   40051
#define IDM_PAGEUSERDAY                 40052
#define IDM_PAGETOOLS                   40053
#define IDM_ALARMADD                    40060
#define IDM_ALARMEDIT                   40061
#define IDM_ALARMDELETE                 40062
#define IDM_ALARMCLEAR                  40063
#define IDM_ALARMPREVIEW                40064
#define IDM_HOLIDAYADD                  40065
#define IDM_HOLIDAYEDIT                 40066
#define IDM_HOLIDAYDELETE               40067
#define IDM_HOLIDAYCLEAR                40068
#define IDM_EXECTOOL                    40070
#define IDM_PAGELAST                    40075
#define IDM_PAGENEXT                    40076
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1053
#define _APS_NEXT_COMMAND_VALUE         40077
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           1001
#endif
#endif
